apiVersion: v1
kind: ServiceAccount
metadata:
  name: kateyes-sa-sa
  namespace: kateyes-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-sa
rules:
- apiGroups: [""]
  resources: ["pods","services","namespaces","endpoints"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-sa
subjects:
- kind: ServiceAccount
  name: kateyes-sa-sa
  namespace: kateyes-sa
roleRef:
  kind: ClusterRole
  name: pods-list-sa
  apiGroup: rbac.authorization.k8s.io
